# Generated by Django 5.1.3 on 2024-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KilometersApp', '0003_remove_profile_phone_profile_encrypted_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='encrypted_phone',
            field=models.TextField(verbose_name='Зашифрованный номер телефона'),
        ),
    ]
