# Generated by Django 5.1.3 on 2024-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KilometersApp', '0006_alter_profile_options_alter_profile_encrypted_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='encrypted_phone',
            field=models.TextField(blank=True, null=True, verbose_name='Зашифрованный номер телефона'),
        ),
    ]
